version: '3'

services:

  frontend:
    image: node:20
    working_dir: /app
    command: bash -c "npm ci && npm start"
    volumes:
      - ./frontend/:/app
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: node:20
    working_dir: /app
    command: bash -c "npm ci && npm start"
    volumes:
      - ./backend/:/app
    depends_on:
      - db
    ports:
      - 1337:1337

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: website-scaffold
      POSTGRES_USER: website-scaffold
      POSTGRES_PASSWORD: website-scaffold
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-volume:
