version: '3'

services:

  frontend:
    image: node:20
    working_dir: /app
    command: bash -c "npm install && npm start"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./frontend/:/app
    environment:
      PORT: ${FRONTEND_PORT:-3002}
      API_URL: http://backend:${BACKEND_PORT:-3001}
      API_TOKEN: ${FRONTEND_API_KEY:-website-scaffold}
    depends_on:
      - backend
    ports:
      - ${FRONTEND_PORT:-3002}:${FRONTEND_PORT:-3002}

  backend:
    image: node:20
    working_dir: /app
    command: bash -c "npm install && npm start"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend/:/app
    environment:
      HOST: ${BACKEND_HOST:-0.0.0.0}
      PORT: ${BACKEND_PORT:-3001}
      KEY: ${BACKEND_KEY:-website-scaffold}
      SECRET: ${BACKEND_SECRET:-website-scaffold}
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: ${DATABASE_PORT:-3000}
      DB_DATABASE: ${DATABASE_NAME:-website-scaffold}
      DB_USER: ${DATABASE_USERNAME:-website-scaffold}
      DB_PASSWORD: ${DATABASE_PASSWORD:-website-scaffold}
      ADMIN_EMAIL: ${BACKEND_INITIAL_ADMIN_EMAIL:-admin@website-scaffold.com}
      ADMIN_PASSWORD: ${BACKEND_INITIAL_ADMIN_PASSWORD:-website-scaffold}
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT:-3001}:${BACKEND_PORT:-3001}

  db:
    image: postgres:12
    environment:
      PGPORT: ${DATABASE_PORT:-3000}
      POSTGRES_DB: ${DATABASE_NAME:-website-scaffold}
      POSTGRES_USER: ${DATABASE_USERNAME:-website-scaffold}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-website-scaffold}
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT:-3000}:${DATABASE_PORT:-3000}

volumes:
  db-volume:
