version: '3'

services:

  frontend:
    image: node:20
    working_dir: /app
    command: bash -c "npm i && npm start"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./frontend/:/app
    env_file:
      - .env
    environment:
      BACKEND_URL: http://backend:${BACKEND_PORT:-1337}
    depends_on:
      - backend
    ports:
      - 3000:3000

  backend:
    image: node:20
    working_dir: /app
    command: bash -c "npm i && npm start"
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./backend/:/app
    env_file:
      - .env
    environment:
      BACKEND_DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT:-1337}:${BACKEND_PORT:-1337}

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${BACKEND_DATABASE_NAME:-website-scaffold}
      POSTGRES_USER: ${BACKEND_DATABASE_USERNAME:-website-scaffold}
      POSTGRES_PASSWORD: ${BACKEND_DATABASE_PASSWORD:-website-scaffold}
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db-volume:
